# https://detekt.dev/docs/introduction/configurations/
build:
  maxIssues: 0

complexity:
  LongMethod:
    active: false
  LongParameterList:
    ignoreDataClasses: true
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    ignoreOverridden: true

style:
  MaxLineLength:
    maxLineLength: 140
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true
